import inv_mng_study as ims

potion = ims.Object('Potion',(1,1),True,0.1,1,99,stack=70)
sword = ims.Object('Sword',(4,2),False,2,2,1)
shield = ims.Object('Shield',(3,3),False,2,2,1)

player = ims.Inventory(10,10)

player.add_object(potion)
print(player.area)
print('#############################')
player.add_object(sword)
print(player.area)
print('#############################')
player.add_object(potion)
print(player.area)
print('#############################')
player.add_object(sword)
print(player.area)
print('#############################')
player.add_object(sword)
print(player.area)
print('#############################')
player.add_object(sword)
print(player.area)
print('#############################')
player.add_object(shield)
print(player.area)
print('#############################')
player.add_object(sword)
print(player.area)
print('#############################')
player.add_object(sword)
print(player.area)
print('#############################')
player.add_object(sword)
print(player.area)
print('#############################')
player.add_object(sword)
print(player.area)
print('#############################')
player.add_object(sword)
print(player.area)
print('#############################')
player.remove_item((2,2))
print(player.area)
print('#############################')
player.remove_item((0,0),70)
print(player.area)
print('#############################')
player.remove_item((0,0),70)
print(player.area)
print('#############################')
player.add_object(shield)
print(player.area)
print('#############################')
player.add_object(shield)
print(player.area)
print('#############################')
print(player.stk[102].stack)
player.add_object(potion)
print(player.area)
print('#############################')
player.add_object(potion)
print(player.area)
print('#############################')

